name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install the package
      run: |
        pip install .

    - name: Validate package.xml
      run: |
        sudo apt-get install -y libxml2-utils
        xmllint --noout package.xml

    - name: Run Python tests
      run: |
        pytest
